kp_development/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('news.urls'), name='news')
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('hello', views.hello, name='hello'),
    path('category/all', views.all_categories, name='all_categories'),
    path('category/<int:category_id>', views.category, name='category'),
    path('news/<int:news_id>', views.news_detail, name='news_detail'),
]

news/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class New(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import New, Category


def hello(request):
    return HttpResponse("Hello, world.")

def all_categories(request):
    categories = Category.objects.all()
    return render(request, 'all_categories.html', {'categories': categories})


def category(request, category_id):
    category = Category.objects.get(id=category_id)
    news = New.objects.filter(categories=category)
    return render(request, 'category.html', {'news': news, 'category': category })


def news_detail(request, news_id):
    news = New.objects.get(id=news_id)
    return render(request, 'news_detail.html', {'news': news})








#
#
#
# - Категорії
# - Новини (в категорії)
# - Детальна сторінка новини

news/templates/all_categories.html
<div>
    <h1>Список категорій</h1>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'news:category' category.id %}"> {{ category.name }} </a></li>
        {% endfor %}
    </ul>
</div>

news/templates/category.html
<h1> {{ category.name }} </h1>

<ul>
    {% for item in news %}
        <li><a href="{% url 'news:news_detail' item.id %}"> {{ item.title }} </a></li>
    {% endfor %}
</ul>

news/templates/news_detail.html
<H1> {{ news.title }} </H1>
<P> {{ news.content }} </P>